import { can } from './shared/permissions.mjs';
const filters={stage:'solicitacoes',work:'',from:'',to:'',query:''};
const emailStatus={ready:'Preparado',sending:'Em andamento',accepted:'Aceito pelo serviço',failed:'Falhou',unknown:'Confirmação pendente'};
export function mountReports(root,data,hooks){
 const {esc,api,attempt,download,session,state}=hooks;
 const works=state.works.filter(w=>can(session,'reportsExport',w.id));
 if(!works.some(w=>w.id===filters.work))filters.work=works[0]?.id||'';
 root.innerHTML=`<div class="page-heading"><div><p class="eyebrow">RELATÓRIOS POR ETAPA</p><h1>Central de relatórios</h1><p class="subtitle">Consulte, exporte o PDF e compartilhe com um colaborador autorizado.</p></div></div>
 <section class="panel"><div class="panel-body"><form id="stage-report-form"><div class="fields"><label>Obra<select name="work" required>${works.map(w=>`<option value="${esc(w.id)}" ${filters.work===w.id?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label><label>Etapa<select name="stage">${Object.entries(data.options.stages).map(([id,label])=>`<option value="${id}" ${id===filters.stage?'selected':''}>${label}</option>`).join('')}</select></label><label>Data inicial<input name="from" type="date" value="${esc(filters.from)}"></label><label>Data final<input name="to" type="date" value="${esc(filters.to)}"></label><label class="wide">Buscar nos registros<input name="query" maxlength="300" value="${esc(filters.query)}" placeholder="Material, fornecedor, código ou finalidade"></label></div><p class="subtitle" id="report-date-help">O período muda conforme a etapa. Estoque usa somente a data final; orçamento apresenta a posição atual.</p><div class="actions"><button class="primary" ${works.length?'':'disabled'}>Gerar relatório</button></div></form></div></section>
 <section class="panel"><div class="panel-head"><h2>Prévia do relatório</h2><button id="report-pdf" disabled>Exportar PDF</button></div><div class="panel-body" id="report-preview"><p>Escolha a obra e a etapa e clique em Gerar relatório.</p></div></section>
 <section class="panel"><div class="panel-head"><h2>Enviar por e-mail</h2></div><div class="panel-body"><p class="note">${data.options.emailConfigured?'O PDF será enviado ao e-mail cadastrado na aba Segurança. O destinatário precisa ter acesso à obra e aos relatórios.':'O envio precisa ser configurado pelo responsável pelo ambiente. A exportação em PDF já está disponível.'}</p><form id="report-mail-form"><label>Colaborador<select name="recipientId" id="report-recipient" required><option value="">Gere um relatório para escolher o destinatário</option></select></label><label>Mensagem (opcional)<textarea name="message" maxlength="2000"></textarea></label><div class="actions"><button id="report-send" class="primary" disabled>Enviar relatório por e-mail</button></div></form></div></section>
 <section class="panel"><div class="panel-head"><h2>Meus envios</h2><small>100 MAIS RECENTES</small></div><div class="panel-body">${data.emails.length?`<div class="table-wrap"><table><thead><tr><th>Etapa / obra</th><th>Colaborador</th><th>Situação</th><th></th></tr></thead><tbody>${data.emails.map(j=>`<tr><td>${esc(data.options.stages[j.stage])}<small>${esc(j.work_id)}</small></td><td>${esc(j.recipient_email)}</td><td>${esc(emailStatus[j.status]||j.status)}<small>${esc(j.last_error||'')}</small></td><td>${(['ready','failed','unknown'].includes(j.status)||(j.status==='sending'&&Date.parse(j.lease_until||0)<Date.now()))?`<button data-mail-retry="${j.id}">Repetir este envio</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhum relatório enviado por você.</p>'}<p class="subtitle">“Aceito pelo serviço” confirma o encaminhamento ao provedor. A entrega na caixa de entrada não é confirmada nesta versão.</p></div></section><p class="error" id="communication-error" role="alert"></p>`;
 let report=null,requestKey=null;
 const form=root.querySelector('#stage-report-form'),pdfButton=root.querySelector('#report-pdf'),sendButton=root.querySelector('#report-send');
 const parameters=()=>Object.fromEntries(new FormData(form));
 form.oninput=()=>{report=null;pdfButton.disabled=true;sendButton.disabled=true;};
 form.onchange=form.oninput;
 form.onsubmit=e=>{e.preventDefault();attempt(async()=>{
  const params=parameters();Object.assign(filters,params);report=await api('/api/reports?'+new URLSearchParams(params));requestKey=crypto.randomUUID();
  root.querySelector('#report-preview').innerHTML=`<p><strong>${esc(report.title)} · ${esc(report.work.name)}</strong></p><p class="subtitle">${esc(report.period)} · ${report.rows.length} linhas</p><p class="note">${esc(report.note)}</p>${report.rows.length?`<div class="table-wrap"><table><thead><tr>${report.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${report.rows.map(r=>`<tr>${r.map(c=>`<td class="report-cell">${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p>Nenhum registro corresponde aos filtros.</p>'}`;
  pdfButton.disabled=false;
  if(can(session,'reportsEmail',params.work)){
   const recipients=await api('/api/reports/recipients?work='+encodeURIComponent(params.work));
   root.querySelector('#report-recipient').innerHTML='<option value="">Selecione o colaborador</option>'+recipients.map(r=>`<option value="${esc(r.id)}">${esc(r.name)} · ${esc(r.email)}</option>`).join('');sendButton.disabled=!data.options.emailConfigured||!recipients.length;
  }
 });};
 pdfButton.onclick=()=>attempt(()=>download('/api/reports?'+new URLSearchParams({...parameters(),format:'pdf',revision:report.revision}),'FeS-'+report.stage+'.pdf'));
 root.querySelector('#report-mail-form').onsubmit=e=>{e.preventDefault();attempt(async()=>{
  if(!report)throw Error('Gere o relatório antes do envio.');const payload={...parameters(),revision:report.revision,...Object.fromEntries(new FormData(e.target))};
  const result=await api('/api/reports/email',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':requestKey},body:JSON.stringify(payload)});
  await hooks.refresh();hooks.toast(result.status==='accepted'?'Relatório aceito pelo serviço de e-mail.':'Confira a situação do envio no histórico.');
 });};
 root.querySelectorAll('[data-mail-retry]').forEach(b=>b.onclick=()=>attempt(async()=>{const r=await api('/api/reports/emails/'+b.dataset.mailRetry+'/retry',{method:'POST'});await hooks.refresh();hooks.toast(emailStatus[r.status]||r.status);}));
}
export function mountNotifications(root,data,hooks){
 const {esc,api,attempt}=hooks;
 root.innerHTML=`<div class="page-heading"><div><p class="eyebrow">SUA OPERAÇÃO</p><h1>Notificações</h1><p class="subtitle">${data.unread} não lida(s). O contador é atualizado automaticamente. Clique em Atualizar para consultar a lista recente.</p></div><button id="notice-read-all">Marcar todas como lidas</button></div><section class="panel"><div class="panel-body">${data.items.length?data.items.map(n=>`<article class="notice ${n.read_at?'':'notice-unread'}"><div><strong>${esc(n.title)}</strong><p>${esc(n.message)}</p><small>${esc(new Date(n.created_at).toLocaleString('pt-BR'))}${n.work_id?' · '+esc(n.work_id):''}</small></div><div class="actions"><a href="#${esc(n.page)}">Abrir etapa</a>${n.read_at?'':`<button data-notice-read="${esc(n.id)}">Marcar como lida</button>`}</div></article>`).join(''):'<p>Você ainda não tem notificações.</p>'}${data.nextOffset!==null?'<button id="notice-next">Ver mais antigas</button>':''}${data.offset?'<button id="notice-first">Voltar às recentes</button>':''}</div></section><p class="error" id="communication-error" role="alert"></p>`;
 const mark=payload=>attempt(async()=>{await api('/api/notifications/read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await hooks.refresh();});
 root.querySelector('#notice-read-all').onclick=()=>mark({all:true});root.querySelectorAll('[data-notice-read]').forEach(b=>b.onclick=()=>mark({id:b.dataset.noticeRead}));
 root.querySelector('#notice-next')?.addEventListener('click',()=>attempt(async()=>{const next=await api('/api/notifications?offset='+data.nextOffset);mountNotifications(root,next,hooks);}));
 root.querySelector('#notice-first')?.addEventListener('click',()=>attempt(hooks.refresh));
}
export function mountDocuments(root,data,hooks){
 const {esc,api,attempt,state,session}=hooks;
 root.innerHTML=`<div class="page-heading"><div><p class="eyebrow">DOCUMENTOS COMPARTILHADOS</p><h1>Importar PDFs</h1><p class="subtitle">Extraia o texto, revise as sugestões e confirme o cadastro no ERP.</p></div></div><section class="panel"><div class="panel-body"><form id="document-form"><div class="fields"><label>Obra<select name="work" id="document-work" required>${state.works.map(w=>`<option value="${esc(w.id)}" ${w.id===data.work?'selected':''}>${esc(w.name)}</option>`).join('')}</select></label><label>PDF<input id="document-file" type="file" accept=".pdf,application/pdf"></label></div><p class="note">Até 10 MB por PDF e 200 páginas. A extração lê até 30 páginas. PDFs digitalizados podem exigir reconhecimento de imagem. Confira nomes, quantidades, unidades, datas e preços antes de salvar.</p><div class="actions"><button class="primary" id="document-import" ${can(session,'documentsImport',data.work)?'':'disabled'}>Importar e extrair texto</button></div></form></div></section><section class="panel"><div class="panel-head"><h2>PDFs da obra</h2><small>200 MAIS RECENTES</small></div><div class="panel-body">${data.items.length?`<div class="table-wrap"><table><thead><tr><th>Arquivo / responsável</th><th>Páginas / extração</th><th>Vínculo</th><th></th></tr></thead><tbody>${data.items.map(d=>`<tr><td>${esc(d.name)}<small>${esc(d.owner_name)}</small></td><td>${d.pages} · ${esc(({extracted:'Texto extraído',partial:'Extração parcial',no_text:'Sem texto selecionável'})[d.extraction_status])}</td><td>${esc(d.linked_record_id||'Aguardando revisão ou vínculo')}</td><td><button data-document="${d.id}">Revisar documento</button></td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhum PDF nesta obra.</p>'}</div></section><p class="error" id="communication-error" role="alert"></p>`;
 const form=root.querySelector('#document-form');root.querySelector('#document-work').onchange=()=>attempt(()=>hooks.changeDocumentWork(form.elements.work.value));
 form.onsubmit=e=>{e.preventDefault();attempt(async()=>{
  const file=root.querySelector('#document-file').files[0];if(!file||!file.name.toLowerCase().endsWith('.pdf')||file.size===0||file.size>10*1024*1024)throw Error('Selecione um PDF com conteúdo de até 10 MB.');
  const result=await api('/api/documents?'+new URLSearchParams({work:form.elements.work.value,name:file.name}),{method:'POST',headers:{'Content-Type':'application/pdf'},body:file});
  await hooks.refresh();hooks.toast(result.duplicate?'Este PDF já foi importado. Abrindo o documento existente.':'PDF importado. Revise os dados antes de cadastrar.');await showDocument(result.id,hooks);
 });};
 root.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>attempt(()=>showDocument(b.dataset.document,hooks)));
}
export async function showDocument(id,hooks){
 const {api,esc,session,state}=hooks,doc=await api('/api/documents/'+id);
 const requests=state.requests.filter(r=>r.work===doc.work_id&&r.status==='quoting'&&(!doc.linked_record_id||doc.linked_record_id===r.id));
 const canImport=can(session,'documentsImport',doc.work_id),canCreate=canImport&&can(session,'create',doc.work_id)&&!doc.imported&&!doc.linked_record_id;
 hooks.modal('Revisar PDF · '+esc(doc.name),`<p class="subtitle">${doc.pages} página(s) · Importado por ${esc(doc.owner_name)}</p>${doc.extraction_status==='no_text'?'<p class="note">Este PDF não contém texto selecionável. O arquivo foi guardado; a extração automática requer OCR, ainda não configurado.</p>':doc.extraction_status==='partial'?'<p class="note">A extração é parcial. Confira também as páginas restantes no PDF.</p>':''}<div class="actions"><button id="document-download">Baixar PDF original</button><button id="document-view">Visualizar PDF</button></div><h3>Texto extraído para conferência</h3><textarea class="pdf-text" readonly>${esc(doc.extracted_text)}</textarea><h3>Itens sugeridos</h3>${doc.suggestions.items.length?`<div class="table-wrap"><table><thead><tr><th>Descrição extraída</th><th>Quantidade</th><th>Unidade</th><th>Preço sugerido</th></tr></thead><tbody>${doc.suggestions.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.qty}</td><td>${esc(i.unit)}</td><td>${i.price??'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="subtitle">Nenhuma tabela foi reconhecida com segurança. Você pode preencher os campos manualmente, usando o texto extraído como referência.</p>'}
 <p class="note">Sugestões precisam de revisão. Nenhum pedido, contrato ou estoque é alterado ao importar o arquivo.</p>
 ${doc.imported?`<p><strong>Cadastro confirmado:</strong> ${esc(doc.imported.record_id)}</p>`:`<div class="actions">${canCreate?'<button id="document-create" class="primary">Revisar e criar solicitação</button>':''}</div>${canImport&&can(session,'quote',doc.work_id)&&requests.length?`<label>Solicitação para a proposta<select id="document-quote-request">${requests.map(r=>`<option value="${r.id}">${esc(r.purpose)} · ${r.id}</option>`).join('')}</select></label><button id="document-quote">Revisar e cadastrar proposta</button>`:''}`}
 ${canImport&&!doc.linked_record_id&&!doc.imported?`<h3>Vincular a um registro existente</h3><form id="document-link-form"><label>Registro<select name="target" required>${[['request',state.requests],['order',state.orders],['contract',state.contracts]].flatMap(([kind,rows])=>rows.filter(r=>r.work===doc.work_id).map(r=>`<option value="${esc(JSON.stringify({kind,recordId:r.id}))}">${esc(r.id)} · ${esc(r.purpose||r.supplier)}</option>`)).join('')}</select></label><button>Salvar vínculo do PDF</button></form>`:doc.linked_record_id?`<p>Vinculado a ${esc(doc.linked_record_id)}</p>`:''}`);
 const modal=document.querySelector('#dialog-content');
 modal.querySelector('#document-download').onclick=()=>hooks.attempt(()=>hooks.download('/api/documents/'+id+'/file',doc.name));
 modal.querySelector('#document-view').onclick=()=>hooks.attempt(async()=>{const blob=await api('/api/documents/'+id+'/file',{},'blob'),url=URL.createObjectURL(blob);hooks.modal('Visualizar PDF · '+esc(doc.name),`<p>Abra o documento no visualizador do navegador para conferir as páginas.</p><a class="button" href="${url}" target="_blank" rel="noopener noreferrer">Abrir PDF original</a>`);document.querySelector('#dialog').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});});
 modal.querySelector('#document-create')?.addEventListener('click',()=>hooks.createFromDocument(doc));
 modal.querySelector('#document-quote')?.addEventListener('click',()=>hooks.quoteFromDocument(doc,modal.querySelector('#document-quote-request').value));
 const link=modal.querySelector('#document-link-form');if(link)link.onsubmit=e=>{e.preventDefault();hooks.attempt(async()=>{await api('/api/documents/'+id+'/link',{method:'POST',headers:{'Content-Type':'application/json'},body:link.elements.target.value});await hooks.refresh();await showDocument(id,hooks);});};
}
