export const services=[{id:'estrutura',name:'04.01 · Estrutura',budget:480000},{id:'alvenaria',name:'06.01 · Alvenaria',budget:180000},{id:'hidraulica',name:'08.02 · Instalações hidráulicas',budget:95000},{id:'nao-previsto',name:'Despesa não prevista',budget:null}];
export const materials=[{id:'cimento',name:'Cimento CP II · 50 kg',unit:'saco'},{id:'bloco',name:'Bloco cerâmico · 14 × 19 × 29 cm',unit:'un'},{id:'tubo',name:'Tubo PVC soldável · 25 mm',unit:'m'}];
export const statusLabels={engineering:'Aguardando engenharia',returned:'Em correção',quoting:'Em cotação',director:'Aguardando diretor',ordered:'Pedido emitido',contracted:'Contrato emitido',received:'Recebido'};
export const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
export const uid=()=>globalThis.crypto.randomUUID();
export function seed(){const state={version:1,requests:[{id:'SOL-001',work:'ELYSIUM',requester:'Marcos · Almoxarifado',purpose:'Alvenaria dos pavimentos tipo',floor:'10º pavimento',date:'2026-10-20',status:'engineering',items:[{material:'bloco',name:materials[1].name,unit:'un',qty:1200,service:'alvenaria',kind:'material'}],history:[{at:'2026-10-04T12:00:00Z',who:'Almoxarifado',text:'Solicitação criada (exemplo fictício).'}],quotes:[]},{id:'SOL-002',work:'BLEND',requester:'Ana · Almoxarifado',purpose:'Concretagem de pilares',floor:'Térreo',date:'2026-10-22',status:'quoting',items:[{material:'cimento',name:materials[0].name,unit:'saco',qty:80,service:'estrutura',kind:'material'}],history:[],quotes:[]},{id:'SOL-003',work:'ELYSIUM',requester:'Marcos · Almoxarifado',purpose:'Instalações dos apartamentos',floor:'12º pavimento',date:'2026-10-23',status:'director',items:[{material:'tubo',name:materials[2].name,unit:'m',qty:300,service:'hidraulica',kind:'material'}],history:[],quotes:[{id:'q1',supplier:'Hidro Sul (fictício)',prices:[14],freight:100,days:5,payment:'28 dias',scope:'Escopo integral',selected:true},{id:'q2',supplier:'Casa das Tubulações (fictício)',prices:[15],freight:0,days:7,payment:'30 dias',scope:'Escopo integral'},{id:'q3',supplier:'Construmais (fictício)',prices:[16],freight:50,days:4,payment:'À vista',scope:'Escopo integral'}]},{id:'SOL-004',work:'BLEND',requester:'Engenharia',purpose:'Serviço de levantamento topográfico',floor:'',date:'2026-10-25',status:'engineering',items:[{name:'Levantamento topográfico',unit:'vb',qty:1,service:'estrutura',kind:'service'}],history:[],quotes:[]}],orders:[],contracts:[],movements:[{id:'initial1',work:'ELYSIUM',material:'bloco',qty:350,kind:'in',who:'Carga demonstrativa',service:'alvenaria',at:'2026-10-04T12:00:00Z'},{id:'initial2',work:'BLEND',material:'cimento',qty:25,kind:'in',who:'Carga demonstrativa',service:'estrutura',at:'2026-10-04T12:00:00Z'},{id:'initial3',work:'ELYSIUM',material:'tubo',qty:60,kind:'in',who:'Carga demonstrativa',service:'hidraulica',at:'2026-10-04T12:00:00Z'}]};for(const r of state.requests){for(const i of r.items){i.neededDate=r.date;i.location=r.floor||'Terreno';}r.decisions=[];}return state;}
// Add the decimal values entered by users without binary floating-point residue.
// The resulting value remains a Number; arithmetic is exact on its decimal representation.
export function quantitySum(a,b){
 const decimal=value=>{if(!Number.isFinite(value))throw Error('Quantidade inválida.');const [mantissa,exponent='0']=String(value).toLowerCase().split('e');const fraction=mantissa.split('.')[1]?.length||0;const scale=fraction-Number(exponent);const digits=BigInt(mantissa.replace('.',''));return scale<0?{digits:digits*10n**BigInt(-scale),scale:0}:{digits,scale};};
 const x=decimal(a),y=decimal(b),scale=Math.max(x.scale,y.scale);
 const sum=x.digits*10n**BigInt(scale-x.scale)+y.digits*10n**BigInt(scale-y.scale);
 const sign=sum<0n?'-':'',digits=(sum<0n?-sum:sum).toString().padStart(scale+1,'0');
 const result=Number(sign+(scale?digits.slice(0,-scale)+'.'+digits.slice(-scale):digits));
 if(!Number.isFinite(result))throw Error('Quantidade inválida.');return result;
}
export function balance(state,work,material,location){return state.movements.filter(m=>m.work===work&&m.material===material&&(location===undefined||(m.location||'')===location)).reduce((s,m)=>quantitySum(s,m.kind==='in'?m.qty:-m.qty),0);}
export function total(request,q){return request.items.reduce((s,i,index)=>s+i.qty*q.prices[index],0)+q.freight;}
export function log(r,who,text){r.history.push({at:new Date().toISOString(),who,text});}
export function approveEngineering(r){if(!['engineering','returned'].includes(r.status))throw Error('Solicitação fora da etapa de engenharia.');if(r.items.some(i=>!i.service))throw Error('Vincule todos os itens ao orçamento.');if(r.items.some(i=>i.service==='nao-previsto')&&!r.justification?.trim())throw Error('Justifique a despesa não prevista.');r.status='quoting';log(r,'Engenharia','Necessidade e vínculos ao orçamento aprovados.');}
export function directorQuote(r,index){return r.quotes.find(q=>q.id===r.decisions?.[index]);}
export function selectedQuote(r,index){return r.quotes.find(q=>q.id===(r.allocations?.[index]||r.quotes.find(q=>q.selected)?.id));}
export function sendDirector(r){if(r.status!=='quoting')throw Error('Solicitação fora da etapa de cotação.');if(!r.quotes.length)throw Error('Cadastre uma proposta.');if(r.quotes.length<3&&!r.exception?.trim())throw Error('São necessárias três propostas ou uma justificativa de exceção.');if(r.items.some((_,index)=>!selectedQuote(r,index)))throw Error('Selecione uma proposta para cada item.');r.status='director';r.decisions=[];log(r,'Suprimentos','Sugestões de fornecedores enviadas ao diretor para decisão.');}
export function reject(r,who,reason){if(!reason?.trim())throw Error('Informe o motivo da devolução.');if(!['engineering','director'].includes(r.status))throw Error('Etapa inválida para devolução.');r.status=r.status==='director'?'quoting':'returned';log(r,who,'Devolvido: '+reason);}
export function approveDirector(state,r){
 if(r.status!=='director')throw Error('Contratação fora da etapa de aprovação.');
 if(r.items.some((_,index)=>!directorQuote(r,index)))throw Error('O diretor deve escolher o fornecedor de cada item.');
 if(r.items.some(i=>!/^\d{4}-\d{2}-\d{2}$/.test(i.estimatedArrival||'')))throw Error('Informe a previsão de chegada de cada item.');
 for(const q of r.quotes){
  const rows=r.items.flatMap((i,index)=>directorQuote(r,index)?.id===q.id?[{...i,price:q.prices[index],received:0,measured:0}]:[]);
  if(!rows.length)continue;
  const common={requestId:r.id,work:r.work,supplier:q.supplier,date:r.date,payment:q.payment,history:[],attachments:[]};
  const goods=rows.filter(i=>i.kind==='material'),services=rows.filter(i=>i.kind==='service');
  if(goods.length)state.orders.push({...common,id:'PED-'+String(state.orders.length+1).padStart(3,'0'),freight:q.freight,total:goods.reduce((s,i)=>s+i.qty*i.price,0)+q.freight,items:goods,receipts:[]});
  if(services.length)state.contracts.push({...common,id:'CTR-'+String(state.contracts.length+1).padStart(3,'0'),freight:goods.length?0:q.freight,total:services.reduce((s,i)=>s+i.qty*i.price,0)+(goods.length?0:q.freight),items:services,measurements:[]});
 }
 r.status=r.items.some(i=>i.kind==='material')?'ordered':'contracted';
 log(r,'Diretor de engenharia','Diretor definiu os fornecedores e aprovou a contratação; documentos emitidos por fornecedor.');
}
export function receive(state,order,quantities,nf,note,attachments=[]){if(!nf?.trim())throw Error('Informe a nota fiscal.');if(quantities.length!==order.items.length||quantities.some((q,i)=>!Number.isFinite(q)||q<0||q>quantitySum(order.items[i].qty,-order.items[i].received))||!quantities.some(q=>q>0))throw Error('Informe quantidades positivas dentro do saldo pendente.');const at=new Date().toISOString();quantities.forEach((qty,index)=>{if(!qty)return;const item=order.items[index];item.received=quantitySum(item.received,qty);state.movements.push({id:uid(),work:order.work,material:item.material,qty,kind:'in',who:'Almoxarifado',service:item.service,at,orderId:order.id,nf});});order.receipts.push({at,nf,note,quantities,attachments});const r=state.requests.find(r=>r.id===order.requestId);if(state.orders.filter(o=>o.requestId===r.id).every(o=>o.items.every(i=>i.received===i.qty))){r.status=state.contracts.some(c=>c.requestId===r.id)?'contracted':'received';}log(r,'Almoxarifado','Recebimento registrado: '+nf);}
export function withdraw(state,{work,material,qty,who,service,floor,location,reservation}){if(!Number.isFinite(qty)||qty<=0||qty>balance(state,work,material,location)||qty>(reservation?reservationLeft(reservation):available(state,work,material,location)))throw Error('Quantidade deve ser positiva e não ultrapassar o estoque disponível.');if(!who?.trim()||!service)throw Error('Informe quem retirou e o serviço de destino.');if(reservation){if(reservation.status!=='active'||reservation.work!==work||reservation.material!==material||(location!==undefined&&(reservation.location||'')!==location))throw Error('Reserva não corresponde a esta saída.');reservation.consumed=quantitySum(reservation.consumed||0,qty);if(reservationLeft(reservation)<=0)reservation.status='consumed';}state.movements.push({id:uid(),work,material,qty,who,service,floor,kind:'out',type:'withdraw',at:new Date().toISOString(),...(location?{location}:{}),...(reservation?{reservationId:reservation.id}:{})});}
export function measure(contract,quantities,period){if(!period?.trim())throw Error('Informe o período da medição.');if(quantities.length!==contract.items.length||quantities.some((q,i)=>!Number.isFinite(q)||q<0||q>quantitySum(contract.items[i].qty,-contract.items[i].measured))||!quantities.some(q=>q>0))throw Error('Medição deve respeitar o saldo contratual.');let value=0;quantities.forEach((q,i)=>{contract.items[i].measured=quantitySum(contract.items[i].measured,q);value+=q*contract.items[i].price;});contract.measurements.push({at:new Date().toISOString(),period,quantities,value});}

export const normalizeText=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterRequests(requests,{query='',status='',from='',to=''}={}){
 const term=normalizeText(query);
 return requests.filter(r=>{
  const text=[r.id,r.work,r.purpose,r.requester,...r.items.flatMap(i=>[i.name,i.location])].join(' ');
  return (!term||normalizeText(text).includes(term))&&(!status||r.status===status)&&(!(from||to)||r.items.some(i=>i.neededDate&&(!from||i.neededDate>=from)&&(!to||i.neededDate<=to)));
 });
}
export function deliveryRows(orders,today){return orders.flatMap(order=>order.items.map((item,index)=>({orderId:order.id,requestId:order.requestId,work:order.work,supplier:order.supplier,item,index,pending:quantitySum(item.qty,-item.received),status:item.received>=item.qty?'complete':item.estimatedArrival&&item.estimatedArrival<today?'late':item.received>0?'partial':'pending'})));}
export function csvContent(rows){return '\ufeff'+rows.map(row=>row.map(value=>{let text=String(value??'');if(/^[\s]*[=+\-@]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}).join(';')).join('\r\n');}
export function validTaxId(value){const d=String(value??'').replace(/\D/g,'');if(![11,14].includes(d.length)||/^(\d)\1+$/.test(d))return false;const digit=n=>{const weights=d.length===11?Array.from({length:n},(_,i)=>n+1-i):(n===12?[5,4,3,2,9,8,7,6,5,4,3,2]:[6,5,4,3,2,9,8,7,6,5,4,3,2]);const sum=weights.reduce((s,w,i)=>s+w*Number(d[i]),0);if(d.length===11){const r=sum*10%11;return r===10?0:r;}const r=sum%11;return r<2?0:11-r;};return d.length===11?digit(9)===Number(d[9])&&digit(10)===Number(d[10]):digit(12)===Number(d[12])&&digit(13)===Number(d[13]);}
export function formatTaxId(value){const d=String(value??'').replace(/\D/g,'');if(d.length===14)return d.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5');if(d.length===11)return d.replace(/^(\d{3})(\d{3})(\d{3})(\d{2})$/,'$1.$2.$3-$4');return String(value??'').trim();}
export function nextMaterialCode(catalog){const last=catalog.reduce((n,m)=>{const match=/^INS-(\d+)$/.exec(m.code||'');return match?Math.max(n,Number(match[1])):n;},0);return 'INS-'+String(last+1).padStart(4,'0');}
export function materialLabel(m){return m?(m.code?m.code+' · ':'')+m.name:'';}
export function stockStatement(state,work,material,{from='',to=''}={}){let saldo=0,opening=0;const rows=[];for(const m of state.movements.filter(m=>m.work===work&&m.material===material&&(!to||m.at.slice(0,10)<=to)).sort((a,b)=>a.at.localeCompare(b.at))){saldo=quantitySum(saldo,m.kind==='in'?m.qty:-m.qty);if(from&&m.at.slice(0,10)<from){opening=saldo;continue;}rows.push({...m,supplier:m.kind==='in'?state.orders.find(o=>o.id===m.orderId)?.supplier||'':'',balance:saldo});}return {opening,rows,closing:saldo};}
export function stockPosition(state,work,material,at=''){return stockStatement(state,work,material,{to:at}).closing;}
export function lastEntry(state,work,material,at=''){const entry=state.movements.filter(m=>m.work===work&&m.material===material&&m.kind==='in'&&(!at||m.at.slice(0,10)<=at)).sort((a,b)=>a.at.localeCompare(b.at)).at(-1);return entry?{...entry,supplier:state.orders.find(o=>o.id===entry.orderId)?.supplier||''}:null;}
export function reservationLeft(r){return quantitySum(r.qty,-(r.consumed||0));}
export function reserved(state,work,material,location){return (state.reservations||[]).filter(r=>r.status==='active'&&r.work===work&&r.material===material&&(location===undefined||(r.location||'')===location)).reduce((s,r)=>quantitySum(s,reservationLeft(r)),0);}
export function available(state,work,material,location){return quantitySum(balance(state,work,material,location),-reserved(state,work,material,location));}
export function closedThrough(state,work){return (state.closings||[]).filter(c=>c.work===work&&c.active).reduce((d,c)=>c.through>d?c.through:d,'');}
export const movementTypes={receipt:'Recebimento',withdraw:'Saída',init:'Saldo inicial',return:'Devolução ao estoque',transfer:'Transferência'};
export function movementType(m){return movementTypes[m.type||(m.kind==='in'?'receipt':'withdraw')];}
export function reserve(state,{work,material,qty,location='',service='',neededDate='',note='',who}){if(!Number.isFinite(qty)||qty<=0||qty>available(state,work,material,location))throw Error('Reserva maior que o estoque disponível.');const r={id:'RES-'+uid(),work,material,qty,consumed:0,location,service,neededDate,note,who,status:'active',at:new Date().toISOString()};(state.reservations??=[]).push(r);return r;}
export function release(r,reason){if(r.status!=='active')throw Error('Reserva já encerrada.');if(!reason?.trim())throw Error('Informe o motivo da liberação.');r.status='released';r.releaseReason=reason;r.releasedAt=new Date().toISOString();}
export function transfer(state,{work,toWork,material,qty,location='',toLocation='',note='',who}){if(work===toWork&&location===toLocation)throw Error('Escolha outra obra ou outro local de destino.');if(!Number.isFinite(qty)||qty<=0||qty>available(state,work,material,location))throw Error('Transferência maior que o estoque disponível.');const id='TRF-'+uid(),at=new Date().toISOString();state.movements.push({id:uid(),transferId:id,work,material,qty,kind:'out',type:'transfer',toWork,toLocation,who,note,at,...(location?{location}:{})},{id:uid(),transferId:id,work:toWork,material,qty,kind:'in',type:'transfer',fromWork:work,fromLocation:location,who,note,at,...(toLocation?{location:toLocation}:{})});return id;}
export function returnToStock(state,{work,material,qty,who,reason,location='',returnOf=''}){if(!Number.isFinite(qty)||qty<=0)throw Error('Quantidade da devolução inválida.');if(!who?.trim()||!reason?.trim())throw Error('Informe quem devolveu e o motivo.');if(returnOf){const out=state.movements.find(m=>m.id===returnOf);if(!out||out.kind!=='out'||out.type==='transfer'||out.work!==work||out.material!==material)throw Error('Saída de origem inválida.');const returned=state.movements.filter(m=>m.returnOf===returnOf).reduce((s,m)=>quantitySum(s,m.qty),0);if(qty>quantitySum(out.qty,-returned))throw Error('Devolução maior que a quantidade retirada.');}state.movements.push({id:uid(),work,material,qty,who,reason,kind:'in',type:'return',at:new Date().toISOString(),...(location?{location}:{}),...(returnOf?{returnOf}:{})});}
export function initStock(state,{work,material,qty,date,location='',note='',who}){if(!Number.isFinite(qty)||qty<=0)throw Error('Saldo inicial inválido.');if(state.movements.some(m=>m.type==='init'&&m.work===work&&m.material===material&&(m.location||'')===location))throw Error('Este insumo já tem saldo inicial nesta obra e local.');state.movements.push({id:uid(),work,material,qty,who,note,kind:'in',type:'init',at:date+'T00:00:00.000Z',...(location?{location}:{})});}
export function closePeriod(state,{work,through,note='',who}){const current=closedThrough(state,work);if(through<=current)throw Error('Escolha uma data posterior ao último fechamento.');const balances=[...new Set(state.movements.filter(m=>m.work===work).map(m=>m.material))].map(material=>({material,qty:stockStatement(state,work,material,{to:through}).closing}));const c={id:'FEC-'+uid(),work,through,note,who,at:new Date().toISOString(),active:true,balances};(state.closings??=[]).push(c);return c;}
export function reopenPeriod(state,{work,reason,who}){if(!reason?.trim())throw Error('Informe o motivo da reabertura.');const c=(state.closings||[]).filter(c=>c.work===work&&c.active).sort((a,b)=>a.through.localeCompare(b.through)).at(-1);if(!c)throw Error('Não há período fechado nesta obra.');c.active=false;c.reopenedBy=who;c.reopenReason=reason;c.reopenedAt=new Date().toISOString();return c;}
export function parseCSV(text){text=String(text).replace(/^﻿/,'');const first=text.split(/\r?\n/,1)[0]||'';const sep=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(c==='"')quoted=false;else cell+=c;}else if(c==='"')quoted=true;else if(c===sep){row.push(cell);cell='';}else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[];}else cell+=c;}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(!rows.length)return [];const header=rows[0].map(h=>h.trim());return rows.slice(1).map((r,n)=>({line:n+2,...Object.fromEntries(header.map((h,i)=>[h,(r[i]??'').trim()]))}));}
export const importColumns={materials:{code:['codigo','cod','codigodoinsumo','codinsumo','codigoinsumo'],name:['descricao','insumo','nome','descricaodoinsumo','material','descricaoinsumo'],unit:['unidade','un','und','unidadedemedida','sigla','unidademedida'],category:['categoria','grupo','familia','classe','grupodeinsumo'],spec:['detalhe','detalhes','especificacao','complemento','observacao','observacoes'],brand:['marca','fabricante']},suppliers:{name:['nomefantasia','fornecedor','nome','credor','nomedocredor'],legalName:['razaosocial','razao'],document:['cnpj','cpf','cnpjcpf','cpfcnpj','documento','cpfoucnpj'],address:['endereco','logradouro'],city:['cidade','municipio'],uf:['uf','estado'],contact:['contato','responsavel'],email:['email'],phone:['telefone','fone','celular'],paymentTerms:['condicaodepagamento','pagamento','prazodepagamento']}};
const columnKey=k=>normalizeText(k).replace(/[^a-z0-9]/g,'');
function pickColumns(row,map){const keys=Object.keys(row).filter(k=>k!=='line');return Object.fromEntries(Object.entries(map).map(([field,names])=>{const k=names.map(n=>keys.find(k=>columnKey(k)===n)).find(Boolean);return [field,k?String(row[k]??'').trim():''];}));}
const limits={code:30,name:300,unit:30,category:100,spec:300,brand:100,legalName:300,document:100,address:300,city:100,contact:300,email:300,phone:100,paymentTerms:200};
export function planImport(state,kind,rows){const plan=[],names=new Set(),keys=new Set();const used=id=>state.movements.some(m=>m.material===id)||state.requests.some(r=>r.items.some(i=>i.material===id));for(const row of rows){const data=pickColumns(row,importColumns[kind]),line=row.line;const skip=reason=>plan.push({line,action:'skip',reason,data});const long=Object.entries(data).find(([k,v])=>v.length>(limits[k]||100));if(long){skip('Campo muito longo: '+long[0]);continue;}
 if(kind==='materials'){data.code=data.code.toUpperCase();if(!data.name||!data.unit){skip('Sem descrição ou unidade');continue;}const nameKey=normalizeText(data.name);if(names.has(nameKey)||(data.code&&keys.has(data.code))){skip('Repetido na planilha');continue;}names.add(nameKey);if(data.code)keys.add(data.code);const byCode=data.code&&state.catalog.find(m=>(m.code||'').toUpperCase()===data.code),byName=state.catalog.find(m=>normalizeText(m.name)===nameKey),target=byCode||byName;if(byCode&&byName&&byCode!==byName){skip('Código e descrição pertencem a insumos diferentes');continue;}if(target){if(target.unit!==data.unit&&used(target.id)){skip('Unidade diferente de um insumo já usado');continue;}if(!data.code)data.code=target.code||'';plan.push({line,action:'update',targetId:target.id,data});}else plan.push({line,action:'create',data});}
 else{if(!data.name){skip('Sem nome do fornecedor');continue;}if(data.document&&!validTaxId(data.document)){skip('CNPJ/CPF inválido');continue;}data.document=formatTaxId(data.document);data.uf=data.uf.toUpperCase();if(data.uf&&!/^[A-Z]{2}$/.test(data.uf)){skip('UF inválida');continue;}const digits=data.document.replace(/\D/g,''),nameKey=normalizeText(data.name);if(names.has(nameKey)||(digits&&keys.has(digits))){skip('Repetido na planilha');continue;}names.add(nameKey);if(digits)keys.add(digits);const byDoc=digits&&state.suppliers.find(s=>(s.document||'').replace(/\D/g,'')===digits),byName=state.suppliers.find(s=>normalizeText(s.name)===nameKey),target=byDoc||byName;if(byDoc&&byName&&byDoc!==byName){skip('CNPJ e nome pertencem a fornecedores diferentes');continue;}if(target){data.name=target.name;plan.push({line,action:'update',targetId:target.id,data});}else plan.push({line,action:'create',data});}}
 return plan;}
export function applyImport(state,kind,plan){let created=0,updated=0;for(const p of plan){if(p.action==='skip')continue;const rows=kind==='materials'?state.catalog:state.suppliers;if(p.action==='update'){const target=rows.find(r=>r.id===p.targetId);for(const [k,v] of Object.entries(p.data))if(v)target[k]=v;updated++;}else{const data={...p.data};if(kind==='materials'&&!data.code)data.code=nextMaterialCode(state.catalog);rows.push({id:(kind==='materials'?'MAT-':'')+uid(),...data});created++;}}return {created,updated,skipped:plan.filter(p=>p.action==='skip').map(({line,reason})=>({line,reason}))};}
