"""Access regression against the local development server; never production."""
import os
from playwright.sync_api import sync_playwright, expect
url='http://127.0.0.1:'+os.environ.get('PORT','3010')
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path=os.environ.get('FES_CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox'])
    page=browser.new_page()
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto(url)
    expect(page.get_by_role('heading',name='Login necessário',exact=True)).to_be_visible()
    expect(page.locator('#identity')).to_have_text('Login necessário')
    expect(page.locator('#refresh')).to_be_disabled()
    page.locator('#dev-persona').select_option('unassigned');page.locator('#dev-login').click()
    expect(page.get_by_role('heading',name='Acesso ao ERP pendente',exact=True)).to_be_visible()
    expect(page.locator('#identity')).to_have_text('Teste · Sem função')
    expect(page.locator('main > .demo').first).to_contain_text('Login reconhecido')
    expect(page.locator('#refresh')).to_be_disabled()
    expect(page.locator('[data-action="audit"]')).to_be_disabled()
    expect(page.locator('#work')).to_be_disabled()
    assert page.request.get(url+'/api/state').status==403
    expect(page.get_by_role('button',name='Verificar acesso')).to_be_enabled()
    page.get_by_role('button',name='Verificar acesso').click()
    expect(page.get_by_role('heading',name='Acesso ao ERP pendente')).to_be_visible()
    expect(page.locator('#refresh')).to_be_disabled()
    # Grant is mocked solely to exercise UI recovery without reload; no real privileges are created.
    page.route('**/api/session',lambda r:r.fulfill(json={'id':'test-unassigned','name':'Teste · Sem função','access':[{'work_id':'TEST','name':'Obra de teste','role':'almoxarifado'}]}))
    page.route('**/api/state',lambda r:r.fulfill(json={'version':2,'revision':0,'requests':[],'orders':[],'contracts':[],'movements':[],'catalog':[],'suppliers':[],'works':[{'id':'TEST','name':'Obra de teste'}],'budgetServices':{}}))
    page.get_by_role('button',name='Verificar acesso').click()
    expect(page.get_by_role('heading',name='Painel de suprimentos',exact=True)).to_be_visible()
    expect(page.locator('#refresh')).to_be_enabled()
    # Revoked access clears previously rendered records and prevents stale navigation.
    page.route('**/api/state',lambda r:r.fulfill(status=403,json={'error':'Acesso revogado.'}))
    page.locator('#refresh').click()
    expect(page.get_by_role('heading',name='Acesso ao ERP pendente')).to_be_visible()
    expect(page.locator('#refresh')).to_be_disabled()
    expect(page.locator('#nav')).to_be_empty()
    page.unroute('**/api/state');page.unroute('**/api/session')
    for failure in ['service','network','html']:
        if failure=='service':page.route('**/api/session',lambda r:r.fulfill(status=503,json={'error':'Serviço indisponível.'}))
        elif failure=='network':page.route('**/api/session',lambda r:r.abort('failed'))
        else:page.route('**/api/session',lambda r:r.fulfill(content_type='text/html',body='<html>Fallback incorreto</html>'))
        page.reload()
        expect(page.get_by_role('heading',name='Servidor indisponível')).to_be_visible()
        expect(page.locator('#identity')).to_have_text('Teste · Sem função')
        expect(page.locator('main > .demo').first).not_to_contain_text('Conectando')
        page.unroute('**/api/session')
    page.route('**/api/session',lambda r:r.fulfill(status=503,json={'error':'Configuração incompleta.','code':'ERP_SETUP_REQUIRED'}))
    page.reload();expect(page.get_by_role('heading',name='Configuração pendente')).to_be_visible();page.unroute('**/api/session')
    # Advance the browser clock while a fetch remains pending, to exercise its real timeout.
    pending_routes=[];page.clock.install();page.route('**/api/session',lambda r:pending_routes.append(r))
    page.reload();expect(page.get_by_role('heading',name='Verificando acesso…')).to_be_visible()
    page.wait_for_timeout(100);page.clock.fast_forward(21000)
    expect(page.get_by_role('heading',name='Servidor indisponível')).to_be_visible()
    assert pending_routes
    for route in pending_routes:route.abort('timedout')
    page.unroute('**/api/session')
    page.locator('#dev-persona').select_option('user1');page.locator('#dev-login').click()
    expect(page.get_by_role('heading',name='Painel de suprimentos',exact=True)).to_be_visible()
    page.request.post(url+'/dev/logout')
    page.locator('#refresh').click()
    expect(page.get_by_role('heading',name='Login necessário')).to_be_visible()
    expect(page.locator('#identity')).to_have_text('Login necessário')
    assert not errors,errors
    browser.close()
print('PASS: ausência de login; login reconhecido sem função; recuperação sem reload; acesso revogado; sessão encerrada; 503; falha de rede; resposta HTML inesperada; configuração pendente; tempo limite.')
