import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,approveEngineering,sendDirector,approveDirector,receive,balance,withdraw,reject,measure,selectedQuote} from '../domain.mjs';
function approveSuggested(s,r){r.decisions=r.items.map((_,i)=>selectedQuote(r,i)?.id);r.items.forEach(i=>i.estimatedArrival='2026-10-18');approveDirector(s,r);}
test('aprovação técnica exige vínculo e justificativa de despesa não prevista',()=>{const r=seed().requests[0];r.items[0].service='';assert.throws(()=>approveEngineering(r),/orçamento/);r.items[0].service='nao-previsto';assert.throws(()=>approveEngineering(r),/Justifique/);r.justification='Escopo adicional';approveEngineering(r);assert.equal(r.status,'quoting');});
test('menos de três fornecedores requer exceção e seleção',()=>{const r=seed().requests[1];r.quotes=[{id:'1',selected:true,prices:[30],freight:0}];assert.throws(()=>sendDirector(r),/três/);r.exception='Fornecedor exclusivo';sendDirector(r);assert.equal(r.status,'director');});
test('pedido só nasce após aprovação do diretor; recebimentos parciais não duplicam estoque',()=>{const s=seed(),r=s.requests[2];assert.equal(s.orders.length,0);approveSuggested(s,r);assert.equal(s.orders.length,1);assert.throws(()=>approveDirector(s,r),/etapa/);const o=s.orders[0];receive(s,o,[100],'NF-1','');assert.equal(o.items[0].received,100);assert.equal(balance(s,'ELYSIUM','tubo'),160);assert.throws(()=>receive(s,o,[201],'NF-2',''),/saldo/);assert.equal(balance(s,'ELYSIUM','tubo'),160);receive(s,o,[200],'NF-2','');assert.equal(r.status,'received');assert.equal(balance(s,'ELYSIUM','tubo'),360);assert.equal(balance(s,'BLEND','tubo'),0);});
test('saída bloqueia saldo negativo e registra serviço e retirante',()=>{const s=seed();assert.throws(()=>withdraw(s,{work:'BLEND',material:'cimento',qty:26,who:'João',service:'estrutura'}),/estoque/);withdraw(s,{work:'BLEND',material:'cimento',qty:10,who:'João',service:'estrutura'});assert.equal(balance(s,'BLEND','cimento'),15);});
test('devolução do diretor volta a suprimentos com motivo no histórico',()=>{const r=seed().requests[2];assert.throws(()=>reject(r,'Diretor',''),/motivo/);reject(r,'Diretor','Rever prazo');assert.equal(r.status,'quoting');assert.match(r.history[0].text,/Rever prazo/);});
test('serviço gera contrato e medição sem entrada de estoque',()=>{const s=seed(),r=s.requests[3];approveEngineering(r);r.quotes=[{id:'1',selected:true,prices:[1000],freight:0}];r.exception='Fornecedor exclusivo';sendDirector(r);approveSuggested(s,r);assert.equal(s.orders.length,0);assert.equal(s.contracts.length,1);const c=s.contracts[0];measure(c,[.4],'01 a 10/10');assert.equal(c.measurements[0].value,400);assert.throws(()=>measure(c,[.7],'11 a 20/10'),/saldo/);assert.equal(s.movements.length,3);});
test('divisão de itens entre fornecedores emite pedidos sem duplicar quantidades',()=>{const s=seed(),r=s.requests[2];r.items.push({...r.items[0],qty:20,material:'cimento',name:'Cimento',unit:'saco'});r.quotes.forEach((q,i)=>q.prices.push(30+i));r.allocations=['q1','q2'];approveSuggested(s,r);assert.equal(s.orders.length,2);assert.equal(s.orders[0].items.length,1);assert.equal(s.orders[1].items.length,1);assert.equal(s.orders[0].items[0].qty,300);assert.equal(s.orders[1].items[0].qty,20);receive(s,s.orders[0],[300],'NF-1','');assert.equal(r.status,'ordered');receive(s,s.orders[1],[20],'NF-2','');assert.equal(r.status,'received');});
test('sugestão de suprimentos não aprova fornecedor; diretor pode escolher alternativa',()=>{const s=seed(),r=s.requests[2];assert.equal(selectedQuote(r,0).id,'q1');assert.throws(()=>approveDirector(s,r),/diretor deve escolher/);r.decisions=['q2'];assert.throws(()=>approveDirector(s,r),/previsão/);r.items[0].estimatedArrival='2026-10-21';approveDirector(s,r);assert.equal(s.orders[0].supplier,'Casa das Tubulações (fictício)');assert.equal(s.orders[0].items[0].price,15);assert.equal(s.orders[0].items[0].estimatedArrival,'2026-10-21');assert.equal(s.orders[0].items[0].neededDate,'2026-10-23');assert.equal(s.orders[0].items[0].location,'12º pavimento');assert.equal(selectedQuote(r,0).id,'q1');});
test('recebimento preserva metadados dos anexos por entrega',()=>{const s=seed(),r=s.requests[2];approveSuggested(s,r);const attachments=[{id:'file-1',name:'nf.pdf',size:20}];receive(s,s.orders[0],[1],'NF-1','',attachments);assert.deepEqual(s.orders[0].receipts[0].attachments,attachments);});
