CREATE TABLE IF NOT EXISTS user_contacts (user_id TEXT PRIMARY KEY REFERENCES security_users(id), email TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, work_id TEXT, record_id TEXT, page TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL, read_at TEXT, event_key TEXT NOT NULL, UNIQUE(user_id,event_key));
CREATE INDEX IF NOT EXISTS notifications_user ON notifications(user_id,created_at DESC,id DESC);
CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, work_id TEXT NOT NULL REFERENCES works(id), owner_id TEXT NOT NULL, owner_name TEXT NOT NULL, name TEXT NOT NULL, size INTEGER NOT NULL, sha256 TEXT NOT NULL, pages INTEGER NOT NULL, extracted_text TEXT NOT NULL, extraction_status TEXT NOT NULL, linked_kind TEXT, linked_record_id TEXT, created_at TEXT NOT NULL, UNIQUE(work_id,sha256));
CREATE TABLE IF NOT EXISTS document_imports (document_id TEXT PRIMARY KEY REFERENCES documents(id), action TEXT NOT NULL, record_id TEXT NOT NULL, actor_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS report_emails (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, recipient_id TEXT NOT NULL, recipient_email TEXT NOT NULL, work_id TEXT NOT NULL, stage TEXT NOT NULL, request_key TEXT NOT NULL, fingerprint TEXT NOT NULL, pdf_key TEXT NOT NULL, payload TEXT NOT NULL, status TEXT NOT NULL, provider_id TEXT, last_error TEXT, created_at TEXT NOT NULL, last_attempt TEXT, lease_until TEXT, UNIQUE(actor_id,request_key));
CREATE TABLE IF NOT EXISTS communication_audit (id TEXT PRIMARY KEY, actor_id TEXT NOT NULL, actor_name TEXT NOT NULL, work_id TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, created_at TEXT NOT NULL, detail TEXT NOT NULL);
INSERT OR IGNORE INTO role_permissions(role,permission) SELECT r.value,p.value FROM json_each('["almoxarifado","engenharia","suprimentos","diretor"]') r CROSS JOIN json_each('["reportsExport","reportsEmail","documentsImport"]') p WHERE NOT EXISTS(SELECT 1 FROM security_migrations WHERE id='communication-permissions');
INSERT OR IGNORE INTO security_migrations(id) VALUES('communication-permissions');
