export const services=[{id:'estrutura',name:'04.01 · Estrutura',budget:480000},{id:'alvenaria',name:'06.01 · Alvenaria',budget:180000},{id:'hidraulica',name:'08.02 · Instalações hidráulicas',budget:95000},{id:'nao-previsto',name:'Despesa não prevista',budget:null}];
export const materials=[{id:'cimento',name:'Cimento CP II · 50 kg',unit:'saco'},{id:'bloco',name:'Bloco cerâmico · 14 × 19 × 29 cm',unit:'un'},{id:'tubo',name:'Tubo PVC soldável · 25 mm',unit:'m'}];
export const statusLabels={engineering:'Aguardando engenharia',returned:'Em correção',quoting:'Em cotação',director:'Aguardando diretor',ordered:'Pedido emitido',contracted:'Contrato emitido',received:'Recebido'};
export const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
export const uid=()=>globalThis.crypto.randomUUID();
export function seed(){const state={version:1,requests:[{id:'SOL-001',work:'ELYSIUM',requester:'Marcos · Almoxarifado',purpose:'Alvenaria dos pavimentos tipo',floor:'10º pavimento',date:'2026-10-20',status:'engineering',items:[{material:'bloco',name:materials[1].name,unit:'un',qty:1200,service:'alvenaria',kind:'material'}],history:[{at:'2026-10-04T12:00:00Z',who:'Almoxarifado',text:'Solicitação criada (exemplo fictício).'}],quotes:[]},{id:'SOL-002',work:'BLEND',requester:'Ana · Almoxarifado',purpose:'Concretagem de pilares',floor:'Térreo',date:'2026-10-22',status:'quoting',items:[{material:'cimento',name:materials[0].name,unit:'saco',qty:80,service:'estrutura',kind:'material'}],history:[],quotes:[]},{id:'SOL-003',work:'ELYSIUM',requester:'Marcos · Almoxarifado',purpose:'Instalações dos apartamentos',floor:'12º pavimento',date:'2026-10-23',status:'director',items:[{material:'tubo',name:materials[2].name,unit:'m',qty:300,service:'hidraulica',kind:'material'}],history:[],quotes:[{id:'q1',supplier:'Hidro Sul (fictício)',prices:[14],freight:100,days:5,payment:'28 dias',scope:'Escopo integral',selected:true},{id:'q2',supplier:'Casa das Tubulações (fictício)',prices:[15],freight:0,days:7,payment:'30 dias',scope:'Escopo integral'},{id:'q3',supplier:'Construmais (fictício)',prices:[16],freight:50,days:4,payment:'À vista',scope:'Escopo integral'}]},{id:'SOL-004',work:'BLEND',requester:'Engenharia',purpose:'Serviço de levantamento topográfico',floor:'',date:'2026-10-25',status:'engineering',items:[{name:'Levantamento topográfico',unit:'vb',qty:1,service:'estrutura',kind:'service'}],history:[],quotes:[]}],orders:[],contracts:[],movements:[{id:'initial1',work:'ELYSIUM',material:'bloco',qty:350,kind:'in',who:'Carga demonstrativa',service:'alvenaria',at:'2026-10-04T12:00:00Z'},{id:'initial2',work:'BLEND',material:'cimento',qty:25,kind:'in',who:'Carga demonstrativa',service:'estrutura',at:'2026-10-04T12:00:00Z'},{id:'initial3',work:'ELYSIUM',material:'tubo',qty:60,kind:'in',who:'Carga demonstrativa',service:'hidraulica',at:'2026-10-04T12:00:00Z'}]};for(const r of state.requests){for(const i of r.items){i.neededDate=r.date;i.location=r.floor||'Terreno';}r.decisions=[];}return state;}
export function balance(state,work,material){return state.movements.filter(m=>m.work===work&&m.material===material).reduce((s,m)=>s+(m.kind==='in'?m.qty:-m.qty),0);}
export function total(request,q){return request.items.reduce((s,i,index)=>s+i.qty*q.prices[index],0)+q.freight;}
export function log(r,who,text){r.history.push({at:new Date().toISOString(),who,text});}
export function approveEngineering(r){if(!['engineering','returned'].includes(r.status))throw Error('Solicitação fora da etapa de engenharia.');if(r.items.some(i=>!i.service))throw Error('Vincule todos os itens ao orçamento.');if(r.items.some(i=>i.service==='nao-previsto')&&!r.justification?.trim())throw Error('Justifique a despesa não prevista.');r.status='quoting';log(r,'Engenharia','Necessidade e vínculos ao orçamento aprovados.');}
export function directorQuote(r,index){return r.quotes.find(q=>q.id===r.decisions?.[index]);}
export function selectedQuote(r,index){return r.quotes.find(q=>q.id===(r.allocations?.[index]||r.quotes.find(q=>q.selected)?.id));}
export function sendDirector(r){if(r.status!=='quoting')throw Error('Solicitação fora da etapa de cotação.');if(!r.quotes.length)throw Error('Cadastre uma proposta.');if(r.quotes.length<3&&!r.exception?.trim())throw Error('São necessárias três propostas ou uma justificativa de exceção.');if(r.items.some((_,index)=>!selectedQuote(r,index)))throw Error('Selecione uma proposta para cada item.');r.status='director';r.decisions=[];log(r,'Suprimentos','Sugestões de fornecedores enviadas ao diretor para decisão.');}
export function reject(r,who,reason){if(!reason?.trim())throw Error('Informe o motivo da devolução.');if(!['engineering','director'].includes(r.status))throw Error('Etapa inválida para devolução.');r.status=r.status==='director'?'quoting':'returned';log(r,who,'Devolvido: '+reason);}
export function approveDirector(state,r){
 if(r.status!=='director')throw Error('Contratação fora da etapa de aprovação.');
 if(r.items.some((_,index)=>!directorQuote(r,index)))throw Error('O diretor deve escolher o fornecedor de cada item.');
 if(r.items.some(i=>!/^\d{4}-\d{2}-\d{2}$/.test(i.estimatedArrival||'')))throw Error('Informe a previsão de chegada de cada item.');
 for(const q of r.quotes){
  const rows=r.items.flatMap((i,index)=>directorQuote(r,index)?.id===q.id?[{...i,price:q.prices[index],received:0,measured:0}]:[]);
  if(!rows.length)continue;
  const common={requestId:r.id,work:r.work,supplier:q.supplier,date:r.date,payment:q.payment,history:[],attachments:[]};
  const goods=rows.filter(i=>i.kind==='material'),services=rows.filter(i=>i.kind==='service');
  if(goods.length)state.orders.push({...common,id:'PED-'+String(state.orders.length+1).padStart(3,'0'),freight:q.freight,total:goods.reduce((s,i)=>s+i.qty*i.price,0)+q.freight,items:goods,receipts:[]});
  if(services.length)state.contracts.push({...common,id:'CTR-'+String(state.contracts.length+1).padStart(3,'0'),freight:goods.length?0:q.freight,total:services.reduce((s,i)=>s+i.qty*i.price,0)+(goods.length?0:q.freight),items:services,measurements:[]});
 }
 r.status=r.items.some(i=>i.kind==='material')?'ordered':'contracted';
 log(r,'Diretor de engenharia','Diretor definiu os fornecedores e aprovou a contratação; documentos emitidos por fornecedor.');
}
export function receive(state,order,quantities,nf,note,attachments=[]){if(!nf?.trim())throw Error('Informe a nota fiscal.');if(quantities.length!==order.items.length||quantities.some((q,i)=>!Number.isFinite(q)||q<0||q>order.items[i].qty-order.items[i].received)||!quantities.some(q=>q>0))throw Error('Informe quantidades positivas dentro do saldo pendente.');const at=new Date().toISOString();quantities.forEach((qty,index)=>{if(!qty)return;const item=order.items[index];item.received+=qty;state.movements.push({id:uid(),work:order.work,material:item.material,qty,kind:'in',who:'Almoxarifado',service:item.service,at,orderId:order.id,nf});});order.receipts.push({at,nf,note,quantities,attachments});const r=state.requests.find(r=>r.id===order.requestId);if(state.orders.filter(o=>o.requestId===r.id).every(o=>o.items.every(i=>i.received===i.qty))){r.status=state.contracts.some(c=>c.requestId===r.id)?'contracted':'received';}log(r,'Almoxarifado','Recebimento registrado: '+nf);}
export function withdraw(state,{work,material,qty,who,service,floor}){if(!Number.isFinite(qty)||qty<=0||qty>balance(state,work,material))throw Error('Quantidade deve ser positiva e não ultrapassar o estoque.');if(!who?.trim()||!service)throw Error('Informe quem retirou e o serviço de destino.');state.movements.push({id:uid(),work,material,qty,who,service,floor,kind:'out',at:new Date().toISOString()});}
export function measure(contract,quantities,period){if(!period?.trim())throw Error('Informe o período da medição.');if(quantities.length!==contract.items.length||quantities.some((q,i)=>!Number.isFinite(q)||q<0||q>contract.items[i].qty-contract.items[i].measured)||!quantities.some(q=>q>0))throw Error('Medição deve respeitar o saldo contratual.');let value=0;quantities.forEach((q,i)=>{contract.items[i].measured+=q;value+=q*contract.items[i].price;});contract.measurements.push({at:new Date().toISOString(),period,quantities,value});}

export const normalizeText=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterRequests(requests,{query='',status='',from='',to=''}={}){
 const term=normalizeText(query);
 return requests.filter(r=>{
  const text=[r.id,r.work,r.purpose,r.requester,...r.items.flatMap(i=>[i.name,i.location])].join(' ');
  return (!term||normalizeText(text).includes(term))&&(!status||r.status===status)&&(!(from||to)||r.items.some(i=>i.neededDate&&(!from||i.neededDate>=from)&&(!to||i.neededDate<=to)));
 });
}
export function deliveryRows(orders,today){return orders.flatMap(order=>order.items.map((item,index)=>({orderId:order.id,requestId:order.requestId,work:order.work,supplier:order.supplier,item,index,pending:item.qty-item.received,status:item.received>=item.qty?'complete':item.estimatedArrival&&item.estimatedArrival<today?'late':item.received>0?'partial':'pending'})));}
export function csvContent(rows){return '\ufeff'+rows.map(row=>row.map(value=>{let text=String(value??'');if(/^[\s]*[=+\-@]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}).join(';')).join('\r\n');}
